apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
data:
  PORT: {{ .Values.appPort | quote }}
  DEBUG: {{ .Values.env.debug | quote }}
  STORAGE: {{ .Values.env.storage }}
  STORAGE_LOCAL_ROOTDIR: {{ .Values.env.storageRootDir }}
  BASIC_AUTH_USER: {{ .Values.env.auth.user }}
  BASIC_AUTH_PASS: {{ .Values.env.auth.password }}
