apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-deployment
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Release.Name }}
          image: {{ .Values.image.tag }}
          ports:
            - containerPort: {{ .Values.appPort }}
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-configmap
          volumeMounts:
              - mountPath: "/var/charts"
                name: chart-storage
      volumes:
        - name: chart-storage
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-pvc
